-- Seed 30 hits: 10 per brand (Ápice, Rituaria, Gocase)
-- All contents use is_hit = TRUE and platform spread across meta/tiktok

-- ── ÁPICE (10 hits) ──────────────────────────────────────────────────────────
WITH apice AS (SELECT id FROM brands WHERE slug = 'apice')

INSERT INTO contents (name, product, brand_id, creator, hook, scenery, description, content_description, platform, is_hit) VALUES

('Sérum Vitamina C - Antes e Depois 30 dias',
 'Sérum Vitamina C 30ml',
 (SELECT id FROM apice),
 '@maria.skincare',
 'Eu não acreditava que ia funcionar até o dia 30 chegar',
 'Banheiro iluminado, espelho com boa iluminação, mostrando pele com manchas melhorando',
 'Resultado real de 30 dias usando Sérum Vitamina C da Ápice. Manchas clarearam, pele mais luminosa e uniforme. #skincare #serumvitaminac #resultado',
 'Abrir com close no rosto mostrando mancha → corte rápido mostrando sérum → timelapse de 30 dias com fotos → revelar resultado final → CTA para comprar',
 'tiktok', TRUE),

('Rotina AM com Protetor Solar Luminous',
 'Protetor Solar Luminous FPS50',
 (SELECT id FROM apice),
 '@ju.beauty',
 'A minha pele mudou quando eu parei de pular o protetor solar de manhã',
 'Mesa de banheiro organizada com produtos, luz natural da manhã',
 'Rotina matinal completa com foco no protetor solar. Pele hidratada e protegida o dia todo. #rotinaAM #protetorsolar #skincareroutine',
 'Mostrar mesa organizada → passo a passo da rotina → destaque no protetor solar → resultado: pele iluminada antes de sair',
 'tiktok', TRUE),

('Anti-idade Redentor - Reação Ao Vivo',
 'Creme Anti-idade Redentor',
 (SELECT id FROM apice),
 '@skincarecombr',
 'Minha mãe de 52 anos testou ao vivo e não acreditou no resultado',
 'Sala de estar acolhedora, mãe e filha juntas, luz natural',
 'Teste ao vivo do Creme Redentor com minha mãe. Resultado imediato visível. #antiidade #skincare #testeproduto',
 'Setup com mãe sentada → aplicar o creme ao vivo → reação dela → zoom no rosto com resultado → depoimento espontâneo',
 'meta', TRUE),

('Tônico Equilibrante - Tutorial Completo',
 'Tônico Equilibrante',
 (SELECT id FROM apice),
 '@belezanaturaloficial',
 'Você provavelmente está usando o tônico errado para o seu tipo de pele',
 'Bancada clean, fundo neutro, produtos bem organizados',
 'Tutorial de como usar o tônico certo para cada tipo de pele. Dicas de especialista. #tonico #cuidadoscomapele #tutorial',
 'Abertura provocativa → explicar tipos de pele → mostrar como aplicar o tônico → dica de bônus → CTA',
 'tiktok', TRUE),

('Máscara Detox - Resultado em 10 Minutos',
 'Máscara Detox de Argila',
 (SELECT id FROM apice),
 '@gatinhodoblogueiro',
 'Coloquei a máscara às 20h e às 20h10 meu rosto estava diferente',
 'Banheiro moderno, toalha branca, espelho grande iluminado',
 'A máscara detox que age em 10 minutos. Poros visíveis antes, invisíveis depois. #mascara #detox #skincare',
 'Aplicar a máscara → timer de 10 minutos acelerado → lavar → zoom nos poros antes vs depois',
 'tiktok', TRUE),

('Óleo Facial Rosas - Noite Perfeita',
 'Óleo Facial de Rosas',
 (SELECT id FROM apice),
 '@noitedecuidados',
 'O óleo que faz minha pele acordar perfeita todo dia',
 'Quarto com luz âmbar, ambiente aconchegante, rotina noturna',
 'Rotina noturna com Óleo Facial de Rosas. Pele acordando hidratada e radiante. #oleofacial #rotinanotturna #skincare',
 'Mostrar quarto ao anoitecer → aplicar óleo em movimentos suaves → voz over sobre benefícios → acordar com pele perfeita no dia seguinte',
 'meta', TRUE),

('Esfoliante Iluminador - Antes e Depois',
 'Esfoliante Suave Iluminador',
 (SELECT id FROM apice),
 '@lucasbeautyy',
 'Minha pele nunca brilhou tanto — mas era só falta de esfoliação',
 'Boxe de banho, vapor, produtos organizados na prateleira',
 'Esfoliação que transforma a pele em um ritual de brilho. Resultado imediato na primeira vez. #esfoliante #peleperfeita #skincare',
 'Comparação de pele antes → processo de esfoliação → enxaguar → revelar pele iluminada → depoimento',
 'tiktok', TRUE),

('Hidratante FPS50 - Comparativo Real',
 'Hidratante Facial FPS50',
 (SELECT id FROM apice),
 '@comparativoskincare',
 'Testei 5 hidratantes com FPS50 e só um não deixou minha pele oleosa',
 'Mesa de comparação com 5 produtos, luz de estúdio',
 'Comparativo honesto de hidratantes com protetor. Só o da Ápice passou no teste de oleosidade. #comparativo #hidratante #fps50',
 'Apresentar 5 produtos → testar cada um → mostrar resultado oleosidade → destaque Ápice → recomendação',
 'meta', TRUE),

('Sérum Vitamina C 60ml - Custo Por Uso',
 'Sérum Vitamina C 60ml',
 (SELECT id FROM apice),
 '@investimentonabra',
 'Calculei o custo por uso e o sérum da Ápice é o mais barato que uso',
 'Mesa clean, calculadora, produtos alinhados',
 'Custo por uso real do Sérum 60ml. Mais econômico que parece. #custoporeuso #skincare #serumvitaminac',
 'Mostrar conta matemática ao vivo → revelar que dura X dias → calcular custo diário → comparar com café → CTA',
 'tiktok', TRUE),

('Rotina Completa Ápice - Em 5 Minutos',
 'Linha completa Ápice',
 (SELECT id FROM apice),
 '@rotinaskincare5min',
 'Minha rotina completa de skincare cabe em 5 minutos — deixo os produtos prontos',
 'Bancada de banheiro, tudo organizado em bandeja, manhã ensolarada',
 'Rotina completa de skincare em 5 minutos com a linha Ápice. Pele pronta para o dia. #rotinaepida #skincare #apice',
 'Mostrar bandeja organizada → aplicar cada produto rapidamente → timer no canto → resultado final → like se gostou',
 'tiktok', TRUE);


-- ── RITUARIA (10 hits) ────────────────────────────────────────────────────────
WITH rituaria AS (SELECT id FROM brands WHERE slug = 'rituaria')

INSERT INTO contents (name, product, brand_id, creator, hook, scenery, description, content_description, platform, is_hit) VALUES

('Ritual do Banho com Óleo Lavanda',
 'Óleo de Banho Lavanda & Camomila',
 (SELECT id FROM rituaria),
 '@pausanobanheiro',
 'Transformei meu banho de 5 minutos em um ritual de 20 e não me arrependo',
 'Banheiro decorado com velas, pétalas, luz baixa, vapor suave',
 'O banho que virou meu momento sagrado do dia. Óleo de Lavanda & Camomila da Rituaria. #ritualdoBath #autocuidado #rituaria',
 'Preparar o banheiro → acender velas → adicionar óleo na água → entrar → voz over sobre parar o mundo por 20 min → sair renovada',
 'tiktok', TRUE),

('Esfoliante de Açúcar - ASMR',
 'Esfoliante Corporal de Açúcar e Baunilha',
 (SELECT id FROM rituaria),
 '@asmrbeautybr',
 'O cheiro desse esfoliante fez minha amiga perguntar que perfume era',
 'Banheiro com iluminação suave, produtos em superfície de madeira, texturas visíveis',
 'ASMR com o esfoliante de Açúcar e Baunilha da Rituaria. O cheiro que todo mundo pergunta. #asmr #esfoliante #rituaria',
 'Close no esfoliante sendo aberto → aplicar na pele com sons → aroma visível no vapor → pele suave como resultado → silêncio intencional no final',
 'tiktok', TRUE),

('Creme Karité - Pele Seca no Inverno',
 'Creme Corporal Manteiga de Karité',
 (SELECT id FROM rituaria),
 '@pelesecanvidade',
 'Passei o inverno inteiro sem pele seca pelo primeiro ano da minha vida',
 'Quarto aconchegante, cobertor, janela com neve ou chuva',
 'O creme que resolveu minha pele seca no inverno. Manteiga de Karité da Rituaria. #peleseca #creme #rituaria',
 'Mostrar pele seca antes → aplicar o creme → close na textura → pele hidratada → depoimento de 30 dias',
 'meta', TRUE),

('Vela Ritual da Noite - Unboxing',
 'Vela Aromática Ritual da Noite',
 (SELECT id FROM rituaria),
 '@unboxingcalmo',
 'Quando acendo essa vela meu apartamento inteiro transforma',
 'Mesa com itens de decoração, fundo escuro, luz da vela acesa',
 'Unboxing da Vela Ritual da Noite. O aroma que transforma qualquer ambiente. #vela #ritualdanoite #rituaria',
 'Mostrar caixa chegando → abrir devagar → sentir o aroma → acender → mostrar ambiente transformado com a luz da vela',
 'tiktok', TRUE),

('Sabonete Artesanal - De Onde Vem',
 'Sabonete Artesanal em Barra',
 (SELECT id FROM rituaria),
 '@origemdosprodutos',
 'Esse sabonete não é feito em fábrica — é feito à mão em pequenos lotes',
 'Ateliê artesanal, mãos trabalhando com argila, luz natural',
 'A história por trás do Sabonete Artesanal da Rituaria. Feito à mão com ingredientes naturais. #artesanal #sabonete #rituaria',
 'Mostrar processo artesanal → ingredientes naturais → mãos moldando → produto final → comparar com sabonete industrial',
 'tiktok', TRUE),

('Hidratante Floral - Rotina de Tarde',
 'Hidratante Corporal Floral',
 (SELECT id FROM rituaria),
 '@tardecomproposito',
 'A minha pausa de tarde de 3 minutos que mudou minha semana',
 'Varanda ou escritório, planta ao fundo, luz natural de tarde',
 'A pausa de tarde que virou ritual. Hidratante Floral da Rituaria no meio do dia. #pausadatarde #hidratante #rituaria',
 'Mostrar trabalho frenético → parar intencionalmente → aplicar hidratante → respirar fundo → voltar renovada',
 'meta', TRUE),

('Bruma Corporal - No Verão',
 'Bruma Corporal Perfumada',
 (SELECT id FROM rituaria),
 '@veraosensorial',
 'A bruma que substituiu meu perfume no verão e salvou minha pele',
 'Praia ou piscina, ar livre, verão, pele bronzeada hidratada',
 'A bruma corporal perfumada que é hidratação e perfume ao mesmo tempo. #brumaritual #verao #rituaria',
 'Aplicar a bruma na pele após sol → close no brilho na pele → cheirar o aroma → comparar com perfume comum → CTA',
 'tiktok', TRUE),

('Kit Ritual do Banho - Presente Perfeito',
 'Kit Ritual do Banho',
 (SELECT id FROM rituaria),
 '@presenteperfeito',
 'O presente que faz a pessoa parar de dizer que não precisa de nada',
 'Mesa de presente, embalagem bonita, laço, decoração clean',
 'O kit que virou meu presente favorito para dar. Kit Ritual do Banho da Rituaria. #presente #rituaria #kitpresente',
 'Mostrar o kit sendo desembrulhado → cada item do kit → montar o ritual completo → reação emocional da presenteada',
 'meta', TRUE),

('Ritual Noturno Completo - Slow Living',
 'Linha Rituaria noturna completa',
 (SELECT id FROM rituaria),
 '@slowlivingnabr',
 'Meu ritual noturno de 30 minutos que me salvou do burnout',
 'Quarto com luz âmbar, vela acesa, produtos em mesa de cabeceira, atmosfera tranquila',
 'O ritual noturno que equilibrou minha saúde mental. Linha noturna da Rituaria. #slowliving #rituarioturno #rituaria',
 'Mostrar dia corrido → transição para quarto calmo → vela acesa → cada produto do ritual → cama preparada → paz como desfecho',
 'tiktok', TRUE),

('Vela Ritual da Manhã - Meditação',
 'Vela Aromática Ritual da Manhã',
 (SELECT id FROM rituaria),
 '@meditacaocriativa',
 '5 minutos de silêncio com essa vela acesa e o dia começa diferente',
 'Tapete de meditação, luz suave da manhã, vela acesa, incenso, paz',
 'Como a Vela da Manhã virou parte da minha meditação diária. #meditacao #ritualdamanha #rituaria',
 'Acordar → acender a vela → mostrar a respiração → silêncio intencional → abrir os olhos → dia com propósito',
 'meta', TRUE);


-- ── GOCASE (10 hits) ──────────────────────────────────────────────────────────
WITH gocase AS (SELECT id FROM brands WHERE slug = 'gocase')

INSERT INTO contents (name, product, brand_id, creator, hook, scenery, description, content_description, platform, is_hit) VALUES

('Case iPhone Drop Test - Resistência',
 'Capa iPhone MagSafe',
 (SELECT id FROM gocase),
 '@techtestador',
 'Joguei o iPhone com a case da Gocase do terceiro andar e vou te mostrar o resultado',
 'Prédio, câmera lenta, iPhone caindo, suspense',
 'O drop test definitivo da Case MagSafe da Gocase. O resultado vai te surpreender. #droptest #case #iphone #gocase',
 'Build up com suspense → mostrar prédio → jogar em câmera lenta → ir buscar → revelar resultado → zoom na case intacta',
 'tiktok', TRUE),

('Setup Gocase - Meu Home Office Virou Arte',
 'Case para MacBook + Case iPhone',
 (SELECT id FROM gocase),
 '@setupperfeitooficial',
 'Meu setup virou a coisa mais esteticamente agradável que já montei',
 'Home office minimalista e estiloso, mesa clean, tudo coordenado',
 'Transformei meu home office em arte com os produtos da Gocase. #setup #homeoffice #gocase',
 'Mostrar setup antes (bagunçado) → revelar setup depois com produtos Gocase → zoom em cada item → like se quiser a lista completa',
 'tiktok', TRUE),

('Unboxing Capa Personalizada - Surpreendi',
 'Case Personalizada iPhone',
 (SELECT id FROM gocase),
 '@surpresadoano',
 'Customizei a capa do celular da minha namorada e ela choro',
 'Sala de estar, embrulho de presente, câmera revelando reação',
 'O presente personalizado que gerou a melhor reação do ano. Case personalizada da Gocase. #personalizado #presente #gocase',
 'Mostrar processo de personalização no site → receber o produto → cena do presente sendo dado → reação da namorada',
 'meta', TRUE),

('Gocase vs Concorrente - Teste de Verdade',
 'Capa iPhone Clear',
 (SELECT id FROM gocase),
 '@comparatechl',
 'Comprei 5 cases de marcas diferentes e testei por 30 dias — honestidade total',
 'Mesa de laboratório improvisada, 5 cases alinhadas, câmera frontal sério',
 'Teste honesto de 30 dias entre 5 cases de marcas diferentes. A Gocase ganhou por esses motivos. #comparativo #case #gocase',
 'Apresentar as 5 cases → testes de resistência → teste de câmera (não interfere na foto?) → teste de encaixe → revelar ranking',
 'tiktok', TRUE),

('Mochila Tech - O Que Cabe Dentro',
 'Mochila Tech Gocase',
 (SELECT id FROM gocase),
 '@organizacaotech',
 'Essa mochila tem espaço para o laptop, iPad, fones e ainda sobra lugar',
 'Mesa de trabalho, produto aberto com itens espalhados ao redor',
 'Tudo que cabe na Mochila Tech da Gocase. Spoiler: é mais que você imagina. #mochila #tech #gocase',
 'Mostrar todos os itens antes → colocar um por um → fechar a mochila → abrir novamente → testar caber mais uma coisa',
 'tiktok', TRUE),

('Carteira MagSafe - Acabei com a Carteira',
 'Carteira MagSafe Gocase',
 (SELECT id FROM gocase),
 '@minimalistabr',
 'Joguei minha carteira fora e só uso isso agora',
 'Mesa clean, celular com carteira MagSafe, café ao lado, estilo minimal',
 'Adeus carteira, olá MagSafe. A carteira magnética da Gocase que mudou minha vida. #magsafe #minimalismo #gocase',
 'Jogar carteira velha → mostrar carteira MagSafe → colocar o essencial → grudar no iPhone → mostrar que é só isso que precisa',
 'tiktok', TRUE),

('Drop Limitado - Como Consegui Antes',
 'Coleção Limitada Gocase',
 (SELECT id FROM gocase),
 '@dropculturebr',
 'Consegui o drop limitado da Gocase antes de esgotar — vou te ensinar o truque',
 'Celular na mão, notificações de aviso, site aberto, agilidade',
 'O guia definitivo para não perder drops limitados da Gocase. #drop #limitado #gocase',
 'Mostrar drop esgotado → revelar truque de notificação → demonstrar ao vivo como ativar → celebrar quando consegue',
 'meta', TRUE),

('Pelúcia Colecionável - Haul Completo',
 'Pelúcias Colecionáveis Gocase',
 (SELECT id FROM gocase),
 '@haulinhabr',
 'Gastei R$ 300 na Gocase e vou te mostrar cada item que recebi',
 'Cama com produtos espalhados, haul unboxing, estilo influencer',
 'Haul completo da Gocase com foco nas pelúcias colecionáveis. Cada item avaliado. #haul #gocase #colecionavel',
 'Abrir caixas uma por uma → mostrar cada pelúcia → ranking pessoal → qual vale mais a pena → CTA',
 'tiktok', TRUE),

('Case MacBook - Produtividade com Estilo',
 'Case para MacBook',
 (SELECT id FROM gocase),
 '@trabalhacomestilo',
 'Minha produtividade aumentou quando meu setup ficou bonito — não é besteira',
 'Café, mesa de co-working, MacBook com case colorida, fones, café',
 'A psicologia do ambiente esteticamente agradável e como a case do MacBook fez diferença. #produtividade #macbook #gocase',
 'Mostrar setup feio → dados de produtividade ruins → revelar setup com case → dados melhoram → teoria da estética na produtividade',
 'meta', TRUE),

('Fones Coloridos - Match com a Roupa',
 'Fones de Ouvido Estilizados Gocase',
 (SELECT id FROM gocase),
 '@matchdiario',
 'Faço match dos meus fones com a roupa todo dia e isso mudou meus outfits',
 'Guarda-roupa aberto, looks coloridos, fones em destaque, espelho',
 'Como combinei meus fones Gocase com cada look da semana. O detalhe que muda tudo. #match #fones #gocase #outfit',
 'Segunda com look → escolher fone da cor → selfie → terça com outro look → novo fone → semana completa com matchs diferentes',
 'tiktok', TRUE);


-- Insert metrics for all 30 contents
-- Using realistic but varied metrics to demonstrate different hit scores

INSERT INTO content_metrics (content_id, click_count, impressions, views, spend, thumbstop_ratio, roas, engagement_rate, date)
SELECT
  c.id,
  (random() * 15000 + 2000)::INT AS click_count,
  (random() * 400000 + 50000)::INT AS impressions,
  (random() * 300000 + 30000)::INT AS views,
  (random() * 8000 + 1000)::NUMERIC(12,2) AS spend,
  (random() * 0.25 + 0.15)::NUMERIC(6,4) AS thumbstop_ratio,
  (random() * 6 + 2)::NUMERIC(8,4) AS roas,
  (random() * 0.10 + 0.03)::NUMERIC(6,4) AS engagement_rate,
  CURRENT_DATE - (random() * 30)::INT AS date
FROM contents c
WHERE c.is_hit = TRUE;
