// Generated by: supabase gen types typescript --linked > lib/supabase/types.ts
// Run after applying migrations to regenerate with actual schema types.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          slug: string
          name: string
          context: string | null
          products_context: string | null
          elevenlabs_voice_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['brands']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['brands']['Insert']>
      }
      contents: {
        Row: {
          id: string
          name: string | null
          product: string | null
          brand_id: string
          creator: string | null
          image_url: string | null
          video_url: string | null
          video_file: string | null
          transcription: string | null
          scenery: string | null
          hook: string | null
          description: string | null
          content_description: string | null
          platform: 'meta' | 'tiktok' | 'archive' | null
          is_hit: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['contents']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['contents']['Insert']>
      }
      content_metrics: {
        Row: {
          id: string
          content_id: string | null
          click_count: number
          impressions: number
          views: number
          spend: number
          thumbstop_ratio: number
          ctr: number
          roas: number
          engagement_rate: number
          date: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['content_metrics']['Row'], 'id' | 'created_at' | 'ctr'>
        Update: Partial<Database['public']['Tables']['content_metrics']['Insert']>
      }
      video_templates: {
        Row: {
          id: string
          brand_id: string
          name: string
          platform: 'tiktok' | 'meta' | 'archive' | null
          aspect_ratio: '9:16' | '1:1' | '16:9' | null
          video_file_url: string
          duration_seconds: number | null
          has_original_audio: boolean
          notes: string | null
          is_default: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['video_templates']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['video_templates']['Insert']>
      }
      external_references: {
        Row: {
          id: string
          title: string | null
          source_brand: string | null
          creator: string | null
          platform: 'tiktok' | 'meta' | 'youtube' | 'instagram' | 'other' | null
          category: string | null
          video_url: string | null
          thumb_url: string | null
          hook: string | null
          description: string | null
          transcription: string | null
          approx_views: number | null
          approx_engagement: number | null
          tags: string[] | null
          notes: string | null
          added_by: string | null
          import_batch_id: string | null
          imported_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['external_references']['Row'], 'id' | 'imported_at' | 'created_at'>
        Update: Partial<Database['public']['Tables']['external_references']['Insert']>
      }
      content_suggestions: {
        Row: {
          id: string
          origin_content_id: string | null
          origin_brand_id: string | null
          target_brand_id: string
          platform: string | null
          is_replicable: boolean
          replicability_reason: string | null
          name: string | null
          product: string | null
          creator: string | null
          transcription: string | null
          scenery: string | null
          hook: string | null
          description: string | null
          content_description: string | null
          briefing: string | null
          output_mode: 'image' | 'video' | null
          image_url: string | null
          audio_url: string | null
          video_template_id: string | null
          final_video_url: string | null
          external_references_used: string[] | null
          estimated_ctr: number | null
          estimated_roas: number | null
          estimated_views: number | null
          estimated_impact_score: number | null
          status: 'draft' | 'approved' | 'rejected' | 'in_play' | 'published' | 'not_replicable'
          ai_model_version: string | null
          ai_generated_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['content_suggestions']['Row'], 'id' | 'ai_generated_at' | 'created_at'>
        Update: Partial<Database['public']['Tables']['content_suggestions']['Insert']>
      }
      alerts: {
        Row: {
          id: string
          type: 'hit' | 'daily_report' | null
          content_id: string | null
          brand_id: string | null
          message_formatted: string
          sent_whatsapp: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['alerts']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['alerts']['Insert']>
      }
      settings: {
        Row: {
          key: string
          value: Json
          updated_at: string
        }
        Insert: { key: string; value: Json; updated_at?: string }
        Update: Partial<Database['public']['Tables']['settings']['Insert']>
      }
    }
    Views: {
      v_replication_matrix: {
        Row: {
          content_id: string
          content_name: string | null
          hook: string | null
          image_url: string | null
          origin_brand_id: string
          origin_brand_name: string
          origin_brand_slug: string
          target_brand_id: string
          target_brand_name: string
          target_brand_slug: string
          suggestion_id: string | null
          status: string | null
          is_replicable: boolean | null
          output_mode: 'image' | 'video' | null
          estimated_impact_score: number | null
        }
      }
    }
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

export type Brand = Database['public']['Tables']['brands']['Row']
export type Content = Database['public']['Tables']['contents']['Row']
export type ContentMetrics = Database['public']['Tables']['content_metrics']['Row']
export type VideoTemplate = Database['public']['Tables']['video_templates']['Row']
export type ExternalReference = Database['public']['Tables']['external_references']['Row']
export type ContentSuggestion = Database['public']['Tables']['content_suggestions']['Row']
export type Alert = Database['public']['Tables']['alerts']['Row']
export type ReplicationMatrixRow = Database['public']['Views']['v_replication_matrix']['Row']
